---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

script:
  - npm run lint:js
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 36a1549d1b826e550dca5a037af2e44fcf1bd8bf  # Set in travis-ci.org dashboard, marked secure
  local-dir: dist
